apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weshopify-db-psvc
spec:
  volumeName: weshopify-db-psv      
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 4Gi